/**
 * Curated list of ~80 well-known crossover artists (film ↔ music).
 * Used by the seed script and cron warm-cache route.
 */
export const CROSSOVER_ARTISTS: string[] = [
  // Actors who became musicians / musicians who became actors
  "Will Smith",
  "Ice Cube",
  "Queen Latifah",
  "LL Cool J",
  "Mark Wahlberg",
  "Jared Leto",
  "Lady Gaga",
  "Cher",
  "Jennifer Lopez",
  "Justin Timberlake",
  "Beyoncé",
  "Drake",
  "Ice-T",
  "Ludacris",
  "Common",
  "Mos Def",
  "André 3000",
  "50 Cent",
  "Snoop Dogg",
  "Tupac Shakur",
  "Eminem",
  "Dolly Parton",
  "Kris Kristofferson",
  "Willie Nelson",
  "Barbra Streisand",
  "Frank Sinatra",
  "Dean Martin",
  "Sammy Davis Jr.",
  "Elvis Presley",
  "David Bowie",
  "Mick Jagger",
  "Tom Waits",
  "Harry Styles",
  "Janelle Monáe",
  "Childish Gambino",
  "Jack Black",
  "Jamie Foxx",
  "Eddie Murphy",
  "Jennifer Hudson",
  "Mandy Moore",
  "Zendaya",
  "Selena Gomez",
  "Miley Cyrus",
  "Demi Lovato",
  "Hilary Duff",
  "Olivia Rodrigo",
  "Ariana Grande",
  "Rihanna",
  "Mary J. Blige",
  "Idris Elba",
  "Ryan Gosling",
  "Jeff Bridges",
  "Keanu Reeves",
  "Johnny Depp",
  "Robert Downey Jr.",
  "Scarlett Johansson",
  "Bette Midler",
  "Liza Minnelli",
  "Whitney Houston",
  "Madonna",
  "Björk",
  "Courtney Love",
  "Meat Loaf",
  "Tim McGraw",
  "Faith Hill",
  "Dwight Yoakam",
  "Chris Isaak",
  "Hailee Steinfeld",
  "Awkwafina",
  "Tyrese Gibson",
  "Bow Wow",
  "Nick Jonas",
  "Joe Jonas",
  "Vanessa Hudgens",
  "Tina Turner",
  "Diana Ross",
  "Lenny Kravitz",
  "Method Man",
  "RZA",
  "Sisqó",
];
