/**
 * Curated list of ~80 well-known crossover artists (film ↔ music).
 * Used by the seed script and cron warm-cache route.
 */
export const CROSSOVER_ARTISTS: string[] = [
  // Actors who became musicians / musicians who became actors
  "Will Smith",
  "Ice Cube",
  "Queen Latifah",
  "LL Cool J",
  "Mark Wahlberg",
  "Jared Leto",
  "Lady Gaga",
  "Cher",
  "Jennifer Lopez",
  "Justin Timberlake",
  "Beyoncé",
  "Drake",
  "Ice-T",
  "Ludacris",
  "Common",
  "Mos Def",
  "André 3000",
  "50 Cent",
  "Snoop Dogg",
  "Tupac Shakur",
  "Eminem",
  "Dolly Parton",
  "Kris Kristofferson",
  "Willie Nelson",
  "Barbra Streisand",
  "Frank Sinatra",
  "Dean Martin",
  "Sammy Davis Jr.",
  "Elvis Presley",
  "David Bowie",
  "Mick Jagger",
  "Tom Waits",
  "Harry Styles",
  "Janelle Monáe",
  "Childish Gambino",
  "Jack Black",
  "Jamie Foxx",
  "Eddie Murphy",
  "Jennifer Hudson",
  "Mandy Moore",
  "Zendaya",
  "Selena Gomez",
  "Miley Cyrus",
  "Demi Lovato",
  "Hilary Duff",
  "Olivia Rodrigo",
  "Ariana Grande",
  "Rihanna",
  "Mary J. Blige",
  "Idris Elba",
  "Ryan Gosling",
  "Jeff Bridges",
  "Keanu Reeves",
  "Johnny Depp",
  "Robert Downey Jr.",
  "Scarlett Johansson",
  "Bette Midler",
  "Liza Minnelli",
  "Whitney Houston",
  "Madonna",
  "Björk",
  "Courtney Love",
  "Meat Loaf",
  "Tim McGraw",
  "Faith Hill",
  "Dwight Yoakam",
  "Chris Isaak",
  "Hailee Steinfeld",
  "Awkwafina",
  "Tyrese Gibson",
  "Bow Wow",
  "Nick Jonas",
  "Joe Jonas",
  "Vanessa Hudgens",
  "Tina Turner",
  "Diana Ross",
  "Lenny Kravitz",
  "Method Man",
  "RZA",
  "Sisqó",

  // Batch 2 — actors with music careers
  "Keke Palmer",
  "John Legend",
  "Alicia Keys",
  "Pharrell Williams",
  "Timbaland",
  "T.I.",
  "Kevin Bacon",
  "Bruce Willis",
  "Billy Bob Thornton",
  "Juliette Lewis",
  "Russell Crowe",
  "Joaquin Phoenix",
  "Dennis Quaid",
  "Kiefer Sutherland",
  "Steven Van Zandt",
  "Henry Rollins",
  "Jada Pinkett Smith",
  "Kristin Chenoweth",
  "Hugh Jackman",
  "Antonio Banderas",
  "Gwyneth Paltrow",
  "Zoë Kravitz",
  "Jaden Smith",
  "Willow Smith",

  // Batch 3 — musicians with film careers
  "Tyler the Creator",
  "A$AP Rocky",
  "Kid Cudi",
  "Kylie Minogue",
  "Phil Collins",
  "Sting",
  "Roger Daltrey",
  "Alice Cooper",
  "Gene Simmons",
  "Ozzy Osbourne",
  "Rob Zombie",
  "Debbie Harry",
  "Grace Jones",
  "Erykah Badu",
  "Lauryn Hill",
  "Wyclef Jean",
  "Nelly",
  "Eve",
  "Brandy",
  "Usher",
  "Machine Gun Kelly",
  "Post Malone",
  "Bad Bunny",
  "Rosalía",
  "Mariah Carey",
  "Billy Idol",

  // Batch 4 — modern crossovers & musical theatre
  "Timothée Chalamet",
  "Florence Pugh",
  "Austin Butler",
  "Troye Sivan",
  "Lizzo",
  "Cynthia Erivo",
  "Leslie Odom Jr.",
  "Ben Platt",
  "Renée Zellweger",
  "Céline Dion",
  "Peter Gabriel",

  // Batch 5 — classic Hollywood & golden age
  "Judy Garland",
  "Gene Kelly",
  "Fred Astaire",
  "Nat King Cole",
  "Harry Belafonte",
  "Julie Andrews",
  "Doris Day",
  "Eartha Kitt",
  "Louis Armstrong",
  "Ella Fitzgerald",

  // Batch 6 — comedians & variety performers
  "Will Ferrell",
  "Adam Sandler",
  "Jim Carrey",
  "Steve Martin",
  "Dan Aykroyd",
  "John Belushi",
  "Tim Curry",
  "Weird Al Yankovic",

  // Batch 7 — international crossovers
  "Shakira",
  "Pitbull",
  "Lin-Manuel Miranda",
  "Rita Moreno",
  "Carmen Miranda",
  "Cliff Richard",
  "Robbie Williams",
  "Craig David",
  "Seal",
  "Annie Lennox",

  // Batch 8 — rock & metal to film
  "Jon Bon Jovi",
  "Flea",
  "Dave Grohl",
  "Iggy Pop",
  "Nick Cave",
  "Tom Morello",
  "Dee Snider",
  "Pat Benatar",
  "Huey Lewis",
  "Rick Springfield",

  // Batch 9 — R&B, soul & pop
  "Janet Jackson",
  "Prince",
  "Ray Charles",
  "Aretha Franklin",
  "Sam Cooke",
  "Isaac Hayes",
  "Curtis Mayfield",
  "Lionel Richie",
  "Luther Vandross",
  "Aaliyah",
  "Ashanti",
  "Christina Aguilera",
  "Pink",
  "Gwen Stefani",
  "Fergie",
  "Jordin Sparks",

  // Batch 10 — country & folk to film
  "Kenny Rogers",
  "Reba McEntire",
  "Keith Urban",
  "Garth Brooks",
  "Johnny Cash",
  "Waylon Jennings",
  "Glen Campbell",
  "Shania Twain",
  "Carrie Underwood",
  "Taylor Swift",

  // Batch 11 — modern & Gen Z
  "Doja Cat",
  "SZA",
  "Tyler Perry",
  "Billie Eilish",
  "Sabrina Carpenter",
  "Dove Cameron",
  "Sofia Carson",
  "Becky G",
  "Cardi B",
  "Megan Thee Stallion",
  "21 Savage",
  "Travis Scott",

  // Batch 12 — wrestling & action crossovers
  "Dwayne Johnson",
  "John Cena",
  "Nick Cannon",
  "Master P",
  "Vanilla Ice",

  // Batch 13 — hip-hop actors (missed earlier)
  "DMX",
  "Busta Rhymes",
  "Ja Rule",
  "Xzibit",
  "Lil Kim",
  "Missy Elliott",
  "Nas",
  "Lil Wayne",
  "The Weeknd",
  "Chris Brown",
  "Bobby Brown",
  "Ne-Yo",
  "Teyana Taylor",
  "Ray J",

  // Batch 14 — dance/disco era & 70s–80s TV crossovers
  "John Travolta",
  "Olivia Newton-John",
  "Patrick Swayze",
  "David Cassidy",
  "Donny Osmond",
  "Michael Jackson",
  "Rick James",
  "Donna Summer",

  // Batch 15 — actors who sing / secret musicians
  "Kevin Costner",
  "Jeff Goldblum",
  "Hugh Laurie",
  "Oscar Isaac",
  "Viggo Mortensen",
  "Brie Larson",
  "Molly Ringwald",
  "Lindsay Lohan",
  "Bella Thorne",
  "Jennifer Love Hewitt",
  "Cara Delevingne",
  "Sissy Spacek",

  // Batch 16 — Broadway & musical film crossovers
  "Idina Menzel",
  "Kristen Bell",
  "Lea Michele",
  "Darren Criss",
  "Josh Groban",
  "Audra McDonald",
  "Sutton Foster",
  "Jeremy Jordan",
  "Daveed Diggs",
  "Billy Porter",

  // Batch 17 — R&B/soul legends in film
  "Vanessa Williams",
  "Patti LaBelle",
  "Gladys Knight",
  "Dionne Warwick",
  "Toni Braxton",
  "Kelly Rowland",
  "Solange Knowles",
  "Mya",
  "Monica",
  "Elton John",
  "RuPaul",
  "Tom Jones",

  // Batch 18 — Disney Channel & Nickelodeon pipeline
  "Victoria Justice",
  "Bella Poarch",
  "Bridgit Mendler",
  "Aly Michalka",
  "AJ Michalka",
  "Ashley Tisdale",
  "Corbin Bleu",
  "Lucas Grabeel",
  "Ross Lynch",
  "Olivia Holt",
  "China Anne McClain",
  "Raven-Symoné",

  // Batch 19 — more international
  "Riz Ahmed",
  "Golshifteh Farahani",
  "Amitabh Bachchan",
  "Shah Rukh Khan",
  "Priyanka Chopra",
  "Rauw Alejandro",
  "J Balvin",
  "Daddy Yankee",
  "Romeo Santos",
  "Marc Anthony",
  "Enrique Iglesias",
  "Ricky Martin",

  // Batch 20 — legacy & final additions
  "Bing Crosby",
  "Bob Hope",
  "Marlene Dietrich",
  "Maurice Chevalier",
  "Paul Robeson",
  "Nina Simone",
  "Josephine Baker",
  "Cab Calloway",
  "Fats Domino",
  "Little Richard",
  "Chuck Berry",
  "BB King",
  "Questlove",
  "Mark McGrath",
  "Jack White",
  "Marilyn Manson",
  "Vin Diesel",
];
