/**
 * Curated list of ~920 well-known crossover artists (film ↔ music).
 * Used by the seed script and cron warm-cache route.
 */
export const CROSSOVER_ARTISTS: string[] = [
  // Actors who became musicians / musicians who became actors
  "Will Smith",
  "Ice Cube",
  "Queen Latifah",
  "LL Cool J",
  "Mark Wahlberg",
  "Jared Leto",
  "Lady Gaga",
  "Cher",
  "Jennifer Lopez",
  "Justin Timberlake",
  "Beyoncé",
  "Drake",
  "Ice-T",
  "Ludacris",
  "Common",
  "Mos Def",
  "André 3000",
  "50 Cent",
  "Snoop Dogg",
  "Tupac Shakur",
  "Eminem",
  "Dolly Parton",
  "Kris Kristofferson",
  "Willie Nelson",
  "Barbra Streisand",
  "Frank Sinatra",
  "Dean Martin",
  "Sammy Davis Jr.",
  "Elvis Presley",
  "David Bowie",
  "Mick Jagger",
  "Tom Waits",
  "Harry Styles",
  "Janelle Monáe",
  "Childish Gambino",
  "Jack Black",
  "Jamie Foxx",
  "Eddie Murphy",
  "Jennifer Hudson",
  "Mandy Moore",
  "Zendaya",
  "Selena Gomez",
  "Miley Cyrus",
  "Demi Lovato",
  "Hilary Duff",
  "Olivia Rodrigo",
  "Ariana Grande",
  "Rihanna",
  "Mary J. Blige",
  "Idris Elba",
  "Ryan Gosling",
  "Jeff Bridges",
  "Keanu Reeves",
  "Johnny Depp",
  "Robert Downey Jr.",
  "Scarlett Johansson",
  "Bette Midler",
  "Liza Minnelli",
  "Whitney Houston",
  "Madonna",
  "Björk",
  "Courtney Love",
  "Meat Loaf",
  "Tim McGraw",
  "Faith Hill",
  "Dwight Yoakam",
  "Chris Isaak",
  "Hailee Steinfeld",
  "Awkwafina",
  "Tyrese Gibson",
  "Bow Wow",
  "Nick Jonas",
  "Joe Jonas",
  "Vanessa Hudgens",
  "Tina Turner",
  "Diana Ross",
  "Lenny Kravitz",
  "Method Man",
  "RZA",
  "Sisqó",

  // Batch 2 — actors with music careers
  "Keke Palmer",
  "John Legend",
  "Alicia Keys",
  "Pharrell Williams",
  "Timbaland",
  "T.I.",
  "Kevin Bacon",
  "Bruce Willis",
  "Billy Bob Thornton",
  "Juliette Lewis",
  "Russell Crowe",
  "Joaquin Phoenix",
  "Dennis Quaid",
  "Kiefer Sutherland",
  "Steven Van Zandt",
  "Henry Rollins",
  "Jada Pinkett Smith",
  "Kristin Chenoweth",
  "Hugh Jackman",
  "Antonio Banderas",
  "Gwyneth Paltrow",
  "Zoë Kravitz",
  "Jaden Smith",
  "Willow Smith",

  // Batch 3 — musicians with film careers
  "Tyler the Creator",
  "A$AP Rocky",
  "Kid Cudi",
  "Kylie Minogue",
  "Phil Collins",
  "Sting",
  "Roger Daltrey",
  "Alice Cooper",
  "Gene Simmons",
  "Ozzy Osbourne",
  "Rob Zombie",
  "Debbie Harry",
  "Grace Jones",
  "Erykah Badu",
  "Lauryn Hill",
  "Wyclef Jean",
  "Nelly",
  "Eve",
  "Brandy",
  "Usher",
  "Machine Gun Kelly",
  "Post Malone",
  "Bad Bunny",
  "Rosalía",
  "Mariah Carey",
  "Billy Idol",

  // Batch 4 — modern crossovers & musical theatre
  "Timothée Chalamet",
  "Florence Pugh",
  "Austin Butler",
  "Troye Sivan",
  "Lizzo",
  "Cynthia Erivo",
  "Leslie Odom Jr.",
  "Ben Platt",
  "Renée Zellweger",
  "Céline Dion",
  "Peter Gabriel",

  // Batch 5 — classic Hollywood & golden age
  "Judy Garland",
  "Gene Kelly",
  "Fred Astaire",
  "Nat King Cole",
  "Harry Belafonte",
  "Julie Andrews",
  "Doris Day",
  "Eartha Kitt",
  "Louis Armstrong",
  "Ella Fitzgerald",

  // Batch 6 — comedians & variety performers
  "Will Ferrell",
  "Adam Sandler",
  "Jim Carrey",
  "Steve Martin",
  "Dan Aykroyd",
  "John Belushi",
  "Tim Curry",
  "Weird Al Yankovic",

  // Batch 7 — international crossovers
  "Shakira",
  "Pitbull",
  "Lin-Manuel Miranda",
  "Rita Moreno",
  "Carmen Miranda",
  "Cliff Richard",
  "Robbie Williams",
  "Craig David",
  "Seal",
  "Annie Lennox",

  // Batch 8 — rock & metal to film
  "Jon Bon Jovi",
  "Flea",
  "Dave Grohl",
  "Iggy Pop",
  "Nick Cave",
  "Tom Morello",
  "Dee Snider",
  "Pat Benatar",
  "Huey Lewis",
  "Rick Springfield",

  // Batch 9 — R&B, soul & pop
  "Janet Jackson",
  "Prince",
  "Ray Charles",
  "Aretha Franklin",
  "Sam Cooke",
  "Isaac Hayes",
  "Curtis Mayfield",
  "Lionel Richie",
  "Luther Vandross",
  "Aaliyah",
  "Ashanti",
  "Christina Aguilera",
  "Pink",
  "Gwen Stefani",
  "Fergie",
  "Jordin Sparks",

  // Batch 10 — country & folk to film
  "Kenny Rogers",
  "Reba McEntire",
  "Keith Urban",
  "Garth Brooks",
  "Johnny Cash",
  "Waylon Jennings",
  "Glen Campbell",
  "Shania Twain",
  "Carrie Underwood",
  "Taylor Swift",

  // Batch 11 — modern & Gen Z
  "Doja Cat",
  "SZA",
  "Tyler Perry",
  "Billie Eilish",
  "Sabrina Carpenter",
  "Dove Cameron",
  "Sofia Carson",
  "Becky G",
  "Cardi B",
  "Megan Thee Stallion",
  "21 Savage",
  "Travis Scott",

  // Batch 12 — wrestling & action crossovers
  "Dwayne Johnson",
  "John Cena",
  "Nick Cannon",
  "Master P",
  "Vanilla Ice",

  // Batch 13 — hip-hop actors (missed earlier)
  "DMX",
  "Busta Rhymes",
  "Ja Rule",
  "Xzibit",
  "Lil Kim",
  "Missy Elliott",
  "Nas",
  "Lil Wayne",
  "The Weeknd",
  "Chris Brown",
  "Bobby Brown",
  "Ne-Yo",
  "Teyana Taylor",
  "Ray J",

  // Batch 14 — dance/disco era & 70s–80s TV crossovers
  "John Travolta",
  "Olivia Newton-John",
  "Patrick Swayze",
  "David Cassidy",
  "Donny Osmond",
  "Michael Jackson",
  "Rick James",
  "Donna Summer",

  // Batch 15 — actors who sing / secret musicians
  "Kevin Costner",
  "Jeff Goldblum",
  "Hugh Laurie",
  "Oscar Isaac",
  "Viggo Mortensen",
  "Brie Larson",
  "Molly Ringwald",
  "Lindsay Lohan",
  "Bella Thorne",
  "Jennifer Love Hewitt",
  "Cara Delevingne",
  "Sissy Spacek",

  // Batch 16 — Broadway & musical film crossovers
  "Idina Menzel",
  "Kristen Bell",
  "Lea Michele",
  "Darren Criss",
  "Josh Groban",
  "Audra McDonald",
  "Sutton Foster",
  "Jeremy Jordan",
  "Daveed Diggs",
  "Billy Porter",

  // Batch 17 — R&B/soul legends in film
  "Vanessa Williams",
  "Patti LaBelle",
  "Gladys Knight",
  "Dionne Warwick",
  "Toni Braxton",
  "Kelly Rowland",
  "Solange Knowles",
  "Mya",
  "Monica",
  "Elton John",
  "RuPaul",
  "Tom Jones",

  // Batch 18 — Disney Channel & Nickelodeon pipeline
  "Victoria Justice",
  "Bella Poarch",
  "Bridgit Mendler",
  "Aly Michalka",
  "AJ Michalka",
  "Ashley Tisdale",
  "Corbin Bleu",
  "Lucas Grabeel",
  "Ross Lynch",
  "Olivia Holt",
  "China Anne McClain",
  "Raven-Symoné",

  // Batch 19 — more international
  "Riz Ahmed",
  "Golshifteh Farahani",
  "Amitabh Bachchan",
  "Shah Rukh Khan",
  "Priyanka Chopra",
  "Rauw Alejandro",
  "J Balvin",
  "Daddy Yankee",
  "Romeo Santos",
  "Marc Anthony",
  "Enrique Iglesias",
  "Ricky Martin",

  // Batch 20 — legacy & final additions
  "Bing Crosby",
  "Bob Hope",
  "Marlene Dietrich",
  "Maurice Chevalier",
  "Paul Robeson",
  "Nina Simone",
  "Josephine Baker",
  "Cab Calloway",
  "Fats Domino",
  "Little Richard",
  "Chuck Berry",
  "BB King",
  "Questlove",
  "Mark McGrath",
  "Jack White",
  "Marilyn Manson",
  "Vin Diesel",

  // Batch 21 — classic rock & prog in film
  "Keith Richards",
  "Ringo Starr",
  "Paul McCartney",
  "George Harrison",
  "Roger Waters",
  "Art Garfunkel",
  "Neil Diamond",
  "John Denver",
  "Barry Manilow",
  "Gordon Lightfoot",

  // Batch 22 — 50s/60s film & music legends
  "Bobby Darin",
  "Connie Francis",
  "Frankie Avalon",
  "Ann-Margret",
  "Debbie Reynolds",
  "Harry Nilsson",
  "Petula Clark",
  "Dusty Springfield",
  "Lulu",
  "Marianne Faithfull",

  // Batch 23 — blaxploitation & soul cinema
  "Richard Pryor",
  "Della Reese",
  "Diahann Carroll",
  "Smokey Robinson",
  "James Brown",
  "Al Green",
  "Stevie Wonder",
  "Chaka Khan",
  "Rick Ross",
  "Irene Cara",

  // Batch 24 — 80s new wave & synth-pop crossovers
  "David Byrne",
  "Danny Elfman",
  "Thomas Dolby",
  "Belinda Carlisle",
  "Cyndi Lauper",
  "Taylor Momsen",
  "Sebastian Bach",
  "Bret Michaels",
  "Chris Jericho",
  "Dave Bautista",

  // Batch 25 — 90s hip-hop & R&B in film
  "Heavy D",
  "Biz Markie",
  "Tone Loc",
  "Redman",
  "Coolio",
  "Ghostface Killah",
  "Kurupt",
  "Jermaine Dupri",
  "Tisha Campbell",
  "Tatyana Ali",

  // Batch 26 — K-pop, J-pop & Asian crossovers
  "Jay Chou",
  "Rain",
  "Miyavi",
  "IU",
  "D.O.",
  "V",
  "Utada Hikaru",
  "Karen Mok",
  "Nicholas Tse",
  "Lisa Manobal",

  // Batch 27 — Latin & telenovela crossovers
  "Thalía",
  "Gloria Estefan",
  "Don Omar",
  "Nicky Jam",
  "Ozuna",
  "Tego Calderón",
  "Paulina Rubio",
  "Maite Perroni",
  "Lucero",
  "Eugenio Derbez",

  // Batch 28 — UK grime, drill & modern British
  "Stormzy",
  "Skepta",
  "Little Simz",
  "Dua Lipa",
  "Ed Sheeran",
  "Sam Smith",
  "David Essex",
  "Adam Ant",
  "Boy George",
  "Gary Numan",

  // Batch 29 — Bollywood & African crossovers
  "Diljit Dosanjh",
  "Farhan Akhtar",
  "Ayushmann Khurrana",
  "Davido",
  "Wizkid",
  "Burna Boy",
  "Tiwa Savage",
  "Tems",
  "Falz",
  "Fela Kuti",

  // Batch 30 — comedians, voice actors & variety
  "Bo Burnham",
  "Flight of the Conchords",
  "Reggie Watts",
  "Seth MacFarlane",
  "Jemaine Clement",
  "Kristen Wiig",
  "Jason Segel",
  "Zac Efron",
  "Josh Gad",
  "Jonathan Groff",

  // Batch 31 — 90s/2000s pop & hip-hop in film
  "Britney Spears",
  "Christina Milian",
  "Jessica Simpson",
  "Ciara",
  "Omarion",
  "Trey Songz",
  "Mario",
  "Lil Mama",
  "Nicki Minaj",
  "Akon",
  "T-Pain",
  "Wiz Khalifa",
  "French Montana",
  "2 Chainz",
  "Big Sean",
  "Chance the Rapper",
  "Offset",
  "Quavo",
  "Future",
  "Young Thug",

  // Batch 32 — classic jazz & big band in film
  "Duke Ellington",
  "Count Basie",
  "Benny Goodman",
  "Dizzy Gillespie",
  "Miles Davis",
  "Billie Holiday",
  "Sarah Vaughan",
  "Tony Bennett",
  "Peggy Lee",
  "Mel Tormé",
  "Vic Damone",
  "Rosemary Clooney",
  "Perry Como",
  "Lena Horne",
  "Dorothy Dandridge",
  "Harry James",
  "Tommy Dorsey",
  "Dinah Washington",
  "Carmen McRae",
  "Chet Baker",

  // Batch 33 — country & Americana deep cuts
  "Alan Jackson",
  "Brad Paisley",
  "Hank Williams Jr.",
  "Merle Haggard",
  "Loretta Lynn",
  "Tammy Wynette",
  "George Jones",
  "Conway Twitty",
  "Randy Travis",
  "Toby Keith",
  "Blake Shelton",
  "Luke Bryan",
  "Miranda Lambert",
  "Kacey Musgraves",
  "Chris Stapleton",
  "Kane Brown",
  "Trace Adkins",
  "George Strait",
  "Emmylou Harris",
  "Vince Gill",

  // Batch 34 — French & European cinema-music
  "Charlotte Gainsbourg",
  "Serge Gainsbourg",
  "Vanessa Paradis",
  "Brigitte Bardot",
  "Jane Birkin",
  "Yves Montand",
  "Charles Aznavour",
  "Jacques Brel",
  "Juliette Gréco",
  "Mylène Farmer",
  "Adriano Celentano",
  "Falco",
  "Nena",
  "Herbert Grönemeyer",
  "Paolo Conte",
  "Andrea Bocelli",
  "Laura Pausini",
  "Julio Iglesias",
  "Sacha Distel",
  "Catherine Deneuve",

  // Batch 35 — modern hip-hop & trap actors
  "Gucci Mane",
  "Pusha T",
  "Kendrick Lamar",
  "J. Cole",
  "Logic",
  "Joey Bada$$",
  "Action Bronson",
  "Vince Staples",
  "Kodak Black",
  "Lil Yachty",
  "Jack Harlow",
  "DaBaby",
  "GloRilla",
  "Ice Spice",
  "Latto",
  "Coi Leray",
  "Kevin Gates",
  "Lil Uzi Vert",
  "Playboi Carti",
  "ScHoolboy Q",

  // Batch 36 — 70s/80s funk, soul & R&B
  "Barry White",
  "Teddy Pendergrass",
  "Marvin Gaye",
  "George Clinton",
  "Billy Ocean",
  "Bootsy Collins",
  "Patti Smith",
  "Sheila E.",
  "Morris Day",
  "El DeBarge",
  "Anita Baker",
  "Toni Basil",
  "Bobby Womack",
  "Deborah Cox",
  "Alexander O'Neal",
  "Vanity",
  "Apollonia",
  "Rick Astley",
  "Terence Trent D'Arby",
  "Macy Gray",

  // Batch 37 — musical film actors who sing
  "Anna Kendrick",
  "Rebel Wilson",
  "Amy Adams",
  "Ewan McGregor",
  "Pierce Brosnan",
  "Nicole Kidman",
  "Reese Witherspoon",
  "Anne Hathaway",
  "Emily Blunt",
  "James Corden",
  "Catherine Zeta-Jones",
  "Taron Egerton",
  "Rami Malek",
  "Joseph Gordon-Levitt",
  "Matthew Broderick",
  "Nathan Lane",
  "Mandy Patinkin",
  "Lea Salonga",
  "Jake Gyllenhaal",
  "Robert Pattinson",

  // Batch 38 — K-pop & K-drama crossovers
  "Suzy Bae",
  "Jang Geun-suk",
  "Lee Seung-gi",
  "Yoona",
  "Suho",
  "Chanyeol",
  "Baekhyun",
  "Siwon",
  "T.O.P",
  "G-Dragon",
  "Taeyang",
  "CL",
  "Sandara Park",
  "Hyuna",
  "Jackson Wang",
  "Mark Tuan",
  "Jinyoung",
  "Seo In-guk",
  "Eric Nam",
  "Henry Lau",

  // Batch 39 — Latin music legends in film
  "Pedro Infante",
  "Jorge Negrete",
  "Vicente Fernández",
  "Alejandro Fernández",
  "Luis Miguel",
  "Juanes",
  "Carlos Vives",
  "Maluma",
  "Anuel AA",
  "Farruko",
  "Ivy Queen",
  "Celia Cruz",
  "Rubén Blades",
  "Héctor Lavoe",
  "Willie Colón",
  "Arcángel",
  "Wisin",
  "Yandel",
  "Olga Tañón",
  "De La Ghetto",

  // Batch 40 — Bollywood playback & film
  "Aamir Khan",
  "Salman Khan",
  "Hrithik Roshan",
  "Ranveer Singh",
  "Alia Bhatt",
  "Shraddha Kapoor",
  "AR Rahman",
  "Sonu Nigam",
  "Lata Mangeshkar",
  "Kishore Kumar",
  "Mohammed Rafi",
  "Asha Bhosle",
  "Rekha",
  "Madhuri Dixit",
  "Aishwarya Rai",
  "Deepika Padukone",
  "Rajinikanth",
  "Kamal Haasan",
  "Vijay",
  "Arijit Singh",

  // Batch 41 — African music & Nollywood
  "Miriam Makeba",
  "Hugh Masekela",
  "Youssou N'Dour",
  "Salif Keita",
  "Angélique Kidjo",
  "Baaba Maal",
  "Asa",
  "Yemi Alade",
  "Mr Eazi",
  "Rema",
  "CKay",
  "Diamond Platnumz",
  "Sarkodie",
  "Shatta Wale",
  "Stonebwoy",
  "Nasty C",
  "Cassper Nyovest",
  "AKA",
  "Brenda Fassie",
  "Yvonne Chaka Chaka",

  // Batch 42 — Middle Eastern, Turkish & Lusophone
  "Amr Diab",
  "Nancy Ajram",
  "Fairuz",
  "Haifa Wehbe",
  "Kadim Al Sahir",
  "Tamer Hosny",
  "Mohamed Mounir",
  "Googoosh",
  "Tarkan",
  "Sezen Aksu",
  "Ibrahim Tatlıses",
  "Ajda Pekkan",
  "Amália Rodrigues",
  "Cesária Évora",
  "Mariza",
  "Ana Moura",
  "Dulce Pontes",
  "Ebi",
  "Dariush",
  "Elissa",

  // Batch 43 — Caribbean & reggae
  "Bob Marley",
  "Jimmy Cliff",
  "Shaggy",
  "Sean Paul",
  "Beenie Man",
  "Buju Banton",
  "Damian Marley",
  "Ziggy Marley",
  "Toots Hibbert",
  "Desmond Dekker",
  "Peter Tosh",
  "Lee Scratch Perry",
  "Protoje",
  "Chronixx",
  "Koffee",
  "Spice",
  "Popcaan",
  "Vybz Kartel",
  "Bounty Killer",
  "Sizzla",

  // Batch 44 — Australian & New Zealand
  "Natalie Imbruglia",
  "Sia",
  "Delta Goodrem",
  "Cody Simpson",
  "Jason Donovan",
  "Peter Andre",
  "John Farnham",
  "Neil Finn",
  "Lorde",
  "Gotye",
  "Tina Arena",
  "Missy Higgins",
  "Vance Joy",
  "Dean Lewis",
  "Guy Sebastian",
  "Jessica Mauboy",
  "Samantha Jade",
  "Jimmy Barnes",
  "Paul Kelly",
  "Tim Minchin",

  // Batch 45 — electronic, DJ & soundtrack composers
  "Moby",
  "Fatboy Slim",
  "Skrillex",
  "Diplo",
  "Calvin Harris",
  "David Guetta",
  "Marshmello",
  "DJ Khaled",
  "Steve Aoki",
  "Mark Ronson",
  "Goldie",
  "Tricky",
  "Trent Reznor",
  "Ryuichi Sakamoto",
  "Atticus Ross",
  "Quincy Jones",
  "Giorgio Moroder",
  "Vangelis",
  "Jean-Michel Jarre",
  "Yanni",

  // Batch 46 — Broadway & West End veterans
  "Bernadette Peters",
  "Patti LuPone",
  "Betty Buckley",
  "Colm Wilkinson",
  "Michael Ball",
  "Alfie Boe",
  "Ramin Karimloo",
  "Laura Benanti",
  "Kelli O'Hara",
  "Norbert Leo Butz",
  "Brian Stokes Mitchell",
  "Raúl Esparza",
  "Chita Rivera",
  "Gwen Verdon",
  "Joel Grey",
  "Ben Vereen",
  "Cheyenne Jackson",
  "Aaron Tveit",
  "Phillipa Soo",
  "Sierra Boggess",

  // Batch 47 — 2010s indie & alt-R&B
  "Bruno Mars",
  "Anderson .Paak",
  "Thundercat",
  "Flying Lotus",
  "Frank Ocean",
  "Miguel",
  "H.E.R.",
  "Khalid",
  "Daniel Caesar",
  "Steve Lacy",
  "Omar Apollo",
  "Giveon",
  "John Mayer",
  "Jack Johnson",
  "Jason Mraz",
  "Hozier",
  "Leon Bridges",
  "Gary Clark Jr.",
  "Tash Sultana",
  "Maggie Rogers",

  // Batch 48 — punk, post-punk & alt-rock in film
  "Joe Strummer",
  "John Lydon",
  "Siouxsie Sioux",
  "Robert Smith",
  "Peter Murphy",
  "Exene Cervenka",
  "John Doe",
  "Lee Ving",
  "Jello Biafra",
  "Mike Patton",
  "Les Claypool",
  "Perry Farrell",
  "Billy Corgan",
  "Chris Cornell",
  "Eddie Vedder",
  "Thom Yorke",
  "Fiona Apple",
  "Mike Watt",
  "Wayne Kramer",
  "Kim Gordon",

  // Batch 49 — 2020s global crossovers
  "Saweetie",
  "Central Cee",
  "Dave",
  "J Hus",
  "Kali Uchis",
  "Karol G",
  "Anitta",
  "Tyla",
  "Amaarae",
  "Ayra Starr",
  "Asake",
  "Russ",
  "Pabllo Vittar",
  "Luísa Sonza",
  "IZA",
  "Headie One",
  "Stefflon Don",
  "Fireboy DML",
  "Omah Lay",
  "Joeboy",

  // Batch 50 — classic TV stars with records
  "David Soul",
  "Jack Wagner",
  "Don Johnson",
  "Telly Savalas",
  "William Shatner",
  "Leonard Nimoy",
  "Rick Nelson",
  "Shelley Fabares",
  "Bobby Sherman",
  "Leif Garrett",
  "Rex Smith",
  "Shaun Cassidy",
  "Andy Gibb",
  "Marie Osmond",
  "Debby Boone",
  "Pat Boone",
  "Dick Van Dyke",
  "Danny Kaye",
  "Robert Goulet",
  "Paul Anka",

  // Batch 51 — Euro pop & Eurovision
  "Agnetha Fältskog",
  "Frida Lyngstad",
  "Robyn",
  "Tove Lo",
  "Zara Larsson",
  "Morten Harket",
  "Marie Fredriksson",
  "Loreen",
  "Conchita Wurst",
  "Nana Mouskouri",
  "Demis Roussos",
  "Goran Bregović",
  "Emir Kusturica",
  "Manu Chao",
  "MC Solaar",
  "Stromae",
  "Angèle",
  "Aya Nakamura",
  "Helena Paparizou",
  "Damiano David",

  // Batch 52 — Chinese, Japanese & SE Asian
  "Andy Lau",
  "Jacky Cheung",
  "Aaron Kwok",
  "Leon Lai",
  "Leslie Cheung",
  "Anita Mui",
  "Faye Wong",
  "Eason Chan",
  "Sammi Cheng",
  "Coco Lee",
  "Show Lo",
  "Rainie Yang",
  "Jolin Tsai",
  "A-Mei",
  "Takeshi Kitano",
  "Ken Hirai",
  "Ayumi Hamasaki",
  "Namie Amuro",
  "Kimura Takuya",
  "Agnes Monica",

  // Batch 53 — comedy & variety acts
  "Bill Murray",
  "Martin Short",
  "Billy Crystal",
  "Chevy Chase",
  "Kyle Gass",
  "Fred Armisen",
  "Andy Samberg",
  "Chris Rock",
  "Dave Chappelle",
  "Kevin Hart",
  "Mike Myers",
  "Dana Carvey",
  "Maya Rudolph",
  "Tiffany Haddish",
  "Ken Jeong",
  "Jordan Peele",
  "Tracy Morgan",
  "Terry Crews",
  "Shaquille O'Neal",
  "Dennis Rodman",

  // Batch 54 — 60s/70s rock legends in film
  "Bob Dylan",
  "John Lennon",
  "Yoko Ono",
  "Eric Clapton",
  "Jimmy Page",
  "Robert Plant",
  "Pete Townshend",
  "Ray Davies",
  "Van Morrison",
  "Neil Young",
  "Joni Mitchell",
  "Leonard Cohen",
  "Joe Cocker",
  "Rod Stewart",
  "Steven Tyler",
  "Ted Nugent",
  "Carlos Santana",
  "Ian Anderson",
  "Rick Wakeman",
  "Donovan",

  // Batch 55 — modern actors who sing
  "Jamie Campbell Bower",
  "Evan Rachel Wood",
  "Jena Malone",
  "Emmy Rossum",
  "Lucy Hale",
  "Leighton Meester",
  "Jana Kramer",
  "Hayden Panettiere",
  "Chloe Bailey",
  "Halle Bailey",
  "Florence Welch",
  "Paloma Faith",
  "Jessie J",
  "Rita Ora",
  "Ellie Goulding",
  "Charli XCX",
  "Grimes",
  "FKA Twigs",
  "Amber Riley",
  "Ezra Miller",
];
